---
# Load yaml or json secure note from LastPass to Ansible variable

- name: Include checking if record exists in LastPass
  include_tasks: tasks/secrets-storage-lastpass-check-record-exists.yml
  vars:
    secret_path: "{{ item.secret_path }}"

- block:
    - name: Get LastPass data
      delegate_to: localhost
      ansible.builtin.command: "lpass show --sync now '{{ item.secret_path }}'"
      register: lastpass_show_result
      changed_when: False

    - name: Remove unwanted LastPass data beginning and return data
      set_fact:
        # The stdout_lines contain 2 lines that we don't want, and then the
        # third line starts with 'Notes: ' and contains the first config field,
        # so we want to trim that.
        secrets_storage_data: "{{ lastpass_show_result.stdout_lines[2:] | join('\n') | replace('Notes: ', '') }}"
  when: secrets_storage_record_exists
